### ISSUE TITLE
25 Mar 10:42:18 - [warn] [contextbrowser] /contextbrowser/flow/:id TypeError: context.getKeys is not a function

### ISSUE THREAD

**Issue by TotallyInformation** [sbarwe/node-red-contrib-contextbrowser#1]
25 Mar 10:42:18 - [warn] [contextbrowser] /contextbrowser/flow/:id TypeError: context.getKeys is not a function

On Windows 10 with Node v6, latest Node-RED

No vars appear in the contextbrowser tab.

**Comment by sbarwe** [comment]
Have just installed on Win10 , node 6.9.5 without issues.

Did you patch node-red as discribed in the installation notes?
The feature request on the node-red forum found not its way to the node-red trello - so unfortunately still need to patch node-red everytime.

**Comment by TotallyInformation** [comment]
OK, that will be it I expect, sorry to have missed that.
