### ISSUE TITLE
Error - context.getKeyes is not a function

### ISSUE THREAD

**Issue by arturmaj** [sbarwe/node-red-contrib-contextbrowser#3]
On Ubuntu 17.04 x86 node red v.0.17.5-git, when I press refresh I am getting:
31 Oct 07:36:17 - [warn] [contextbrowser] /contextbrowser/flow/:id TypeError: context.getKeys is not a function

**Comment by sbarwe** [comment]
Please update to Version 0.0.4 of contextbrowser

**Comment by arturmaj** [comment]
Thank you for the plugin. It is working.
